import nodemailer from 'nodemailer';

let transporter;

function getTransporter() {
  if (!transporter) {
    transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: parseInt(process.env.SMTP_PORT || '587', 10),
      secure: process.env.SMTP_SECURE === 'true',
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });
  }
  return transporter;
}

export async function deliverEmail(deliveryConfig, report) {
  const { to, subject_prefix } = deliveryConfig;
  const prefix = subject_prefix || '[ReportBot]';

  const htmlTable = formatHtmlTable(report);
  const csvAttachment = formatCsv(report);

  await getTransporter().sendMail({
    from: process.env.SMTP_FROM || process.env.SMTP_USER,
    to: Array.isArray(to) ? to.join(', ') : to,
    subject: `${prefix} ${report.pipelineName} — ${new Date().toISOString().slice(0, 10)}`,
    html: `
      <h2>${report.pipelineName}</h2>
      <p>${report.rowCount} rows returned</p>
      ${htmlTable}
      ${report.alert ? `<p style="color:red;font-weight:bold;">⚠ Alert: ${report.alert}</p>` : ''}
      <p style="color:#888;font-size:12px;">Generated by ReportBot at ${new Date().toISOString()}</p>
    `,
    attachments: [{
      filename: `${report.pipelineName.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.csv`,
      content: csvAttachment,
      contentType: 'text/csv',
    }],
  });
}

function formatHtmlTable(report) {
  if (!report.columns.length) return '<p>No data</p>';
  const maxRows = 50;
  const displayRows = report.rows.slice(0, maxRows);

  let html = '<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;font-family:monospace;font-size:13px;">';
  html += '<tr>' + report.columns.map(c => `<th style="background:#f0f0f0;">${c}</th>`).join('') + '</tr>';
  for (const row of displayRows) {
    html += '<tr>' + report.columns.map(c => `<td>${row[c] ?? ''}</td>`).join('') + '</tr>';
  }
  html += '</table>';
  if (report.rows.length > maxRows) {
    html += `<p style="color:#888;">Showing ${maxRows} of ${report.rows.length} rows. Full data in CSV attachment.</p>`;
  }
  return html;
}

function formatCsv(report) {
  if (!report.columns.length) return '';
  const escape = (v) => {
    const s = String(v ?? '');
    return s.includes(',') || s.includes('"') || s.includes('\n') ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const lines = [report.columns.map(escape).join(',')];
  for (const row of report.rows) {
    lines.push(report.columns.map(c => escape(row[c])).join(','));
  }
  return lines.join('\n');
}
